<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ddd</groupId>
        <artifactId>ddd</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>ddd-application</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.ddd</groupId>
            <artifactId>ddd-model</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ddd</groupId>
            <artifactId>ddd-domain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
    </dependencies>
</project>
